dist: trusty
sudo: required
language: go

go:
  - 1.10.x

go_import_path: github.com/trustpilot/beat-exporter

services:
  - docker

before_script:
  - make dependencies

script:
  - make travis

branches:
  only: master