on:
  release:
    types: [published]
name: handle-release
jobs:
  artifacts:
    name: Create and upload release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code at release tag
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: Get dependencies
        run: |
          go mod download

      - name: Build executables
        run: |
          ./build.sh

      - name: Create artifact archives
        run: |
          ./create-artifacts.sh

      - name: Upload artifacts archives
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: './.release/*'

  docker:
    name: Publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: Get dependencies
        run: |
          go mod download

      - name: Build executables
        run: |
          ./build.sh

      - name: Build and push docker image with version tags
        uses: jerray/publish-docker-action@v1.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: trustpilot/beat-exporter
          auto_tag: true

      - name: Build and push docker image with latest tag
        uses: jerray/publish-docker-action@v1.0.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: trustpilot/beat-exporter
          tags: latest